channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pyyaml=5.3.1
  - scipy=1.5.0
  - scanpy=1.5.1
  - leidenalg=0.7.0
  - louvain=0.6.1
  - plotnine=0.7.0
  - harmonypy=0.0.4
  - scrublet=0.2.1
  - bbknn=1.3.9
  - kneed=0.6.0
  - keras-gpu=2.3.1
  - tensorflow-gpu=2.2.0
  - dask-ml=1.2.0
  - dask-jobqueue=0.7.1
  - joblib=0.14.1
  - scikit-learn=0.23.1
