channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pyyaml=5.3.1
  - pandas=1.0.5
  - scipy=1.4.1
  - numpy=1.18.5
  - scanpy=1.6.0
  - leidenalg=0.8.3
  - louvain=0.6.1
  - plotnine=0.7.1
  - harmonypy=0.0.5
  - scrublet=0.2.1
  - bbknn=1.3.12
  - kneed=0.7.0
  - keras-gpu=2.4.3
  - tensorflow-gpu=2.2.0
  - scikit-learn=0.23.2
  - joblib=0.17.0
  - pip
  - pip:
    - cellex=1.2.1
