channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pandas=1.0.5
  - scipy=1.5.0
  - scanpy=1.5.1
  - plotnine=0.7.0
  - r-dplyr=1.0.2
  - r-optparse=1.6.6
  - r-dirichletreg=0.7_0
